version: '3'
services:
  exemplo-service:
    container_name: ps-exemplo-api
    build: ""
    restart: always
    volumes:
      - ../:/var/www/symfony
    networks:
      - ps-exemplo-api-network

  nginx-exemplo:
    build: nginx
    container_name: ps-nginx-exemplo-api
    restart: always
    ports:
      - '5555:80'
    volumes:
      - /log-nginx:/var/log/nginx
    networks:
      - ps-exemplo-api-network

networks:
  ps-exemplo-api-network:
    driver: bridge

